function plot_rapid_cvar_from_csv(resultsDir)
%PLOT_RAPID_CVAR_FROM_CSV Generate publication-quality CVaR plots.
%
%   plot_rapid_cvar_from_csv()
%   plot_rapid_cvar_from_csv(resultsDir)
%
% Required files in resultsDir:
%   rapid_cvar_ablation_summary.csv
%   rapid_cvar_ablation_per_seed.csv
%   rapid_cvar_ablation_paired_differences.csv
%
% Generated files:
%   rapid_cvar_ablation_metrics_from_csv.pdf/.png
%   rapid_cvar_ablation_paired_from_csv.pdf/.png
%   rapid_cvar_ablation_differences_from_csv.pdf/.png

    if nargin < 1 || isempty(resultsDir)
        resultsDir = fullfile( ...
            pwd, ...
            'results', ...
            'cvar_ablation', ...
            'cvar_ablation_completed_files');
    end

    if ~exist(resultsDir, 'dir')
        error('Results folder not found: %s', resultsDir);
    end

    summaryFile = fullfile(resultsDir, ...
        'rapid_cvar_ablation_summary.csv');

    perSeedFile = fullfile(resultsDir, ...
        'rapid_cvar_ablation_per_seed.csv');

    pairedFile = fullfile(resultsDir, ...
        'rapid_cvar_ablation_paired_differences.csv');

    assert_file_exists(summaryFile);
    assert_file_exists(perSeedFile);
    assert_file_exists(pairedFile);

    summary = readtable(summaryFile, ...
        'VariableNamingRule', 'preserve');

    perSeed = readtable(perSeedFile, ...
        'VariableNamingRule', 'preserve');

    paired = readtable(pairedFile, ...
        'VariableNamingRule', 'preserve');

    validate_columns(summary, { ...
        'Lambda', ...
        'RMSE_mean', ...
        'RMSE_std', ...
        'ISE_mean', ...
        'ISE_std', ...
        'ISE_CVaR', ...
        'ISE_worst', ...
        'Overshoot_mean', ...
        'Overshoot_std', ...
        'TimeInBand_mean', ...
        'TimeInBand_std'});

    validate_columns(perSeed, { ...
        'seed', ...
        'lambda_cvar', ...
        'rmse', ...
        'ise_h', ...
        'peak_overshoot', ...
        'time_in_band_pct', ...
        'EF_energy_h', ...
        'max_amplitude'});

    validate_columns(paired, { ...
        'seed', ...
        'delta_RMSE', ...
        'delta_ISE', ...
        'delta_overshoot', ...
        'delta_time_in_band_pct', ...
        'delta_EF_energy_h', ...
        'delta_max_amplitude'});

    make_summary_figure(summary, resultsDir);
    make_paired_figure(perSeed, resultsDir);
    make_difference_figure(paired, resultsDir);

    fprintf('\nPublication-quality plots generated:\n');

    fprintf('%s\n', fullfile(resultsDir, ...
        'rapid_cvar_ablation_metrics_from_csv.pdf'));

    fprintf('%s\n', fullfile(resultsDir, ...
        'rapid_cvar_ablation_paired_from_csv.pdf'));

    fprintf('%s\n', fullfile(resultsDir, ...
        'rapid_cvar_ablation_differences_from_csv.pdf'));
end


function make_summary_figure(S, resultsDir)
%MAKE_SUMMARY_FIGURE Plot aggregate statistics across seeds.

    labels = arrayfun( ...
        @(x) sprintf('\\lambda=%.1f', x), ...
        S.Lambda, ...
        'UniformOutput', false);

    x = 1:height(S);

    fig = figure( ...
        'Color', 'w', ...
        'Position', [50 50 1800 1250], ...
        'Renderer', 'painters');

    tiledlayout(fig, 2, 2, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    %--------------------------------------------------------------%
    % RMSE
    %--------------------------------------------------------------%
    ax1 = nexttile;

    bar_with_error( ...
        ax1, ...
        x, ...
        S.RMSE_mean, ...
        S.RMSE_std, ...
        labels, ...
        'RMSE', ...
        'Across-seed tracking RMSE');

    %--------------------------------------------------------------%
    % ISE
    %--------------------------------------------------------------%
    ax2 = nexttile;

    bar_with_error( ...
        ax2, ...
        x, ...
        S.ISE_mean, ...
        S.ISE_std, ...
        labels, ...
        'ISE (a.u.^2 h)', ...
        'Across-seed tracking ISE');

    %--------------------------------------------------------------%
    % Mean, empirical CVaR, and worst ISE
    %--------------------------------------------------------------%
    ax3 = nexttile;
    hold(ax3, 'on');

    Y = [ ...
        S.ISE_mean, ...
        S.ISE_CVaR, ...
        S.ISE_worst];

    bar(ax3, x, Y, ...
        'grouped', ...
        'LineWidth', 1.5);

    set(ax3, ...
        'XTick', x, ...
        'XTickLabel', labels, ...
        'TickLabelInterpreter', 'tex');

    ylabel(ax3, ...
        'ISE (a.u.^2 h)', ...
        'Interpreter', 'tex');

    title(ax3, ...
        'Mean, upper-tail CVaR, and worst ISE', ...
        'Interpreter', 'tex');

    legend(ax3, { ...
        'Mean', ...
        'Empirical upper-tail CVaR', ...
        'Worst seed'}, ...
        'Location', 'best', ...
        'Interpreter', 'tex');

    grid(ax3, 'on');

    %--------------------------------------------------------------%
    % Time in target band
    %--------------------------------------------------------------%
    ax4 = nexttile;

    bar_with_error( ...
        ax4, ...
        x, ...
        S.TimeInBand_mean, ...
        S.TimeInBand_std, ...
        labels, ...
        'Time in \pm5% band (%)', ...
        'Fraction of simulation within target band');

    format_figure(fig);

    baseName = fullfile(resultsDir, ...
        'rapid_cvar_ablation_metrics_from_csv');

    save_figure(fig, baseName);

    close(fig);
end


function make_paired_figure(T, resultsDir)
%MAKE_PAIRED_FIGURE Plot paired seed-wise controller comparisons.

    lambda0 = 0.0;
    lambda1 = 0.6;

    T0 = T(abs(T.lambda_cvar-lambda0) < 1e-12, :);
    T1 = T(abs(T.lambda_cvar-lambda1) < 1e-12, :);

    commonSeeds = intersect(T0.seed, T1.seed);

    if isempty(commonSeeds)
        warning(['No paired lambda=0 and lambda=0.6 ' ...
            'random seeds were found.']);
        return;
    end

    [T0, T1] = align_by_seed(T0, T1, commonSeeds);

    fig = figure( ...
        'Color', 'w', ...
        'Position', [50 50 1800 1250], ...
        'Renderer', 'painters');

    tiledlayout(fig, 2, 2, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    paired_panel( ...
        nexttile, ...
        T0.rmse, ...
        T1.rmse, ...
        commonSeeds, ...
        'RMSE', ...
        'Paired tracking RMSE');

    paired_panel( ...
        nexttile, ...
        T0.ise_h, ...
        T1.ise_h, ...
        commonSeeds, ...
        'ISE (a.u.^2 h)', ...
        'Paired tracking ISE');

    paired_panel( ...
        nexttile, ...
        T0.time_in_band_pct, ...
        T1.time_in_band_pct, ...
        commonSeeds, ...
        'Time in \pm5% band (%)', ...
        'Paired time within target band');

    paired_panel( ...
        nexttile, ...
        T0.EF_energy_h, ...
        T1.EF_energy_h, ...
        commonSeeds, ...
        'EF energy (a.u.^2 h)', ...
        'Paired EF energy');

    format_figure(fig);

    baseName = fullfile(resultsDir, ...
        'rapid_cvar_ablation_paired_from_csv');

    save_figure(fig, baseName);

    close(fig);
end


function make_difference_figure(D, resultsDir)
%MAKE_DIFFERENCE_FIGURE Plot lambda=0.6 minus lambda=0 differences.

    metrics = { ...
        'delta_RMSE', ...
        'delta_ISE', ...
        'delta_time_in_band_pct', ...
        'delta_EF_energy_h'};

    ylabels = { ...
        '\Delta RMSE', ...
        '\Delta ISE (a.u.^2 h)', ...
        '\Delta time in band (percentage points)', ...
        '\Delta EF energy (a.u.^2 h)'};

    titles = { ...
        'RMSE difference', ...
        'ISE difference', ...
        'Target-band difference', ...
        'EF-energy difference'};

    fig = figure( ...
        'Color', 'w', ...
        'Position', [50 50 1800 1250], ...
        'Renderer', 'painters');

    tiledlayout(fig, 2, 2, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    for i = 1:4
        ax = nexttile;
        values = D.(metrics{i});

        bar(ax, ...
            D.seed, ...
            values, ...
            0.68, ...
            'LineWidth', 1.5);

        yline(ax, ...
            0, ...
            '--k', ...
            'LineWidth', 2.2);

        xlabel(ax, ...
            'Paired random seed', ...
            'Interpreter', 'tex');

        ylabel(ax, ...
            ylabels{i}, ...
            'Interpreter', 'tex');

        title(ax, ...
            titles{i}, ...
            'Interpreter', 'tex');

        grid(ax, 'on');

        if strcmp(metrics{i}, 'delta_time_in_band_pct')
            subtitle(ax, ...
                'Positive favors \lambda=0.6', ...
                'Interpreter', 'tex');
        else
            subtitle(ax, ...
                'Negative favors \lambda=0.6', ...
                'Interpreter', 'tex');
        end
    end

    format_figure(fig);

    baseName = fullfile(resultsDir, ...
        'rapid_cvar_ablation_differences_from_csv');

    save_figure(fig, baseName);

    close(fig);
end


function bar_with_error(ax, x, values, errors, ...
        labels, yLabel, ttl)
%BAR_WITH_ERROR Draw a bar chart with standard-deviation error bars.

    hold(ax, 'on');

    bar(ax, ...
        x, ...
        values, ...
        0.68, ...
        'LineWidth', 1.5);

    errorbar(ax, ...
        x, ...
        values, ...
        errors, ...
        'k.', ...
        'LineWidth', 2.5, ...
        'CapSize', 18);

    set(ax, ...
        'XTick', x, ...
        'XTickLabel', labels, ...
        'TickLabelInterpreter', 'tex');

    ylabel(ax, ...
        yLabel, ...
        'Interpreter', 'tex');

    title(ax, ...
        ttl, ...
        'Interpreter', 'tex');

    grid(ax, 'on');
end


function paired_panel(ax, values0, values1, seeds, yLabel, ttl)
%PAIRED_PANEL Plot paired lambda=0 and lambda=0.6 results.

    hold(ax, 'on');

    x = [1, 2];

    for i = 1:numel(seeds)
        plot(ax, ...
            x, ...
            [values0(i), values1(i)], ...
            '-o', ...
            'LineWidth', 2.4, ...
            'MarkerSize', 10, ...
            'DisplayName', sprintf('Seed %d', seeds(i)));
    end

    mean0 = mean(values0, 'omitnan');
    mean1 = mean(values1, 'omitnan');

    plot(ax, ...
        x, ...
        [mean0, mean1], ...
        '-s', ...
        'LineWidth', 4.0, ...
        'MarkerSize', 13, ...
        'MarkerFaceColor', 'w', ...
        'DisplayName', 'Mean');

    set(ax, ...
        'XTick', x, ...
        'XTickLabel', {'\lambda=0', '\lambda=0.6'}, ...
        'TickLabelInterpreter', 'tex');

    xlim(ax, [0.75, 2.25]);

    ylabel(ax, ...
        yLabel, ...
        'Interpreter', 'tex');

    title(ax, ...
        ttl, ...
        'Interpreter', 'tex');

    grid(ax, 'on');

    legend(ax, ...
        'Location', 'best', ...
        'Interpreter', 'tex');
end


function [T0, T1] = align_by_seed(T0, T1, commonSeeds)
%ALIGN_BY_SEED Put both controller tables in the same seed order.

    T0aligned = T0([],:);
    T1aligned = T1([],:);

    for i = 1:numel(commonSeeds)
        seed = commonSeeds(i);

        row0 = T0(T0.seed == seed, :);
        row1 = T1(T1.seed == seed, :);

        T0aligned = [T0aligned; row0(1,:)]; %#ok<AGROW>
        T1aligned = [T1aligned; row1(1,:)]; %#ok<AGROW>
    end

    T0 = T0aligned;
    T1 = T1aligned;
end


function format_figure(fig)
%FORMAT_FIGURE Apply large publication-quality fonts.

    axesHandles = findall(fig, 'Type', 'axes');

    for k = 1:numel(axesHandles)
        ax = axesHandles(k);

        % Tick-label font and axes appearance
        ax.FontSize = 20;
        ax.FontWeight = 'normal';
        ax.LineWidth = 1.7;
        ax.Box = 'on';
        ax.TickDir = 'out';
        ax.TickLength = [0.012 0.012];
        ax.Layer = 'top';

        % Axis-label fonts
        ax.XLabel.FontSize = 23;
        ax.XLabel.FontWeight = 'normal';

        ax.YLabel.FontSize = 23;
        ax.YLabel.FontWeight = 'normal';

        % Main-title font
        ax.Title.FontSize = 24;
        ax.Title.FontWeight = 'bold';

        % Subtitle font
        if isprop(ax, 'Subtitle')
            ax.Subtitle.FontSize = 19;
            ax.Subtitle.FontWeight = 'normal';
        end
    end

    % Legend fonts
    legendHandles = findall(fig, 'Type', 'legend');

    for k = 1:numel(legendHandles)
        legendHandles(k).FontSize = 18;
        legendHandles(k).LineWidth = 1.2;
        legendHandles(k).Box = 'on';
    end

    drawnow;
end


function save_figure(fig, baseName)
%SAVE_FIGURE Save a vector PDF and a 600-dpi PNG.

    drawnow;

    % Vector PDF: preferred for the manuscript
    try
        exportgraphics(fig, ...
            [baseName '.pdf'], ...
            'ContentType', 'vector', ...
            'BackgroundColor', 'white');
    catch ME
        warning(ME.identifier, '%s', ME.message);

        print(fig, ...
            [baseName '.pdf'], ...
            '-dpdf', ...
            '-painters', ...
            '-bestfit');
    end

    % High-resolution raster image
    try
        exportgraphics(fig, ...
            [baseName '.png'], ...
            'Resolution', 600, ...
            'BackgroundColor', 'white');
    catch ME
        warning(ME.identifier, '%s', ME.message);

        print(fig, ...
            [baseName '.png'], ...
            '-dpng', ...
            '-r600');
    end
end


function assert_file_exists(filename)
%ASSERT_FILE_EXISTS Verify that a required file exists.

    if ~exist(filename, 'file')
        error('Required CSV file not found: %s', filename);
    end
end


function validate_columns(T, required)
%VALIDATE_COLUMNS Verify required table columns.

    names = T.Properties.VariableNames;
    missing = required(~ismember(required, names));

    if ~isempty(missing)
        error('CSV file is missing columns: %s', ...
            strjoin(missing, ', '));
    end
end