addpath(genpath(fileparts(fileparts(mfilename('fullpath')))));

OUT = run_rapid_clean5(25, struct( ...
    'rng_seed', 7, ...
    'do_plots', true, ...
    'verbose', true));

rapid_plot_measurement_bias_diagnostics(OUT);
